# Generated by Django 3.1.3 on 2021-08-11 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0003_auto_20210811_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('TRANS GENDER', 'TRANS GENDER')], default='MALE', max_length=20),
        ),
        migrations.CreateModel(
            name='RegistrationID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.CharField(max_length=20)),
                ('studentRoll', models.CharField(max_length=5)),
                ('idFrom_Student_RegistrationID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='StudentManagement.student')),
            ],
        ),
    ]
