# Generated by Django 3.1.3 on 2021-08-11 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0004_auto_20210811_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationid',
            name='idFrom_Student_RegistrationID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='StudentManagement.student'),
        ),
    ]
