# Generated by Django 3.1.3 on 2021-08-11 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0005_auto_20210811_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationid',
            old_name='idFrom_Student_RegistrationID',
            new_name='Student_RegistrationID',
        ),
    ]
