# Generated by Django 3.1.3 on 2021-08-11 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0006_auto_20210811_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationid',
            old_name='Student_RegistrationID',
            new_name='idFrom_Student_RegistrationID',
        ),
    ]
