# Generated by Django 3.1.3 on 2021-08-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0007_auto_20210812_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('TRANS_GENDER', 'TRANS GENDER')], default='MALE', max_length=20),
        ),
    ]
