# Generated by Django 3.1.3 on 2021-08-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0008_auto_20210812_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phoneNumber',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
