# Generated by Django 3.1.3 on 2021-08-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0009_auto_20210812_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationid',
            name='studentID',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
