# Generated by Django 3.1.3 on 2021-08-12 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0010_auto_20210812_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationid',
            name='idFrom_Student_RegistrationID',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='StudentManagement.student'),
        ),
    ]
