# Generated by Django 3.1.3 on 2021-09-14 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0011_auto_20210812_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationid',
            name='idFrom_Student_RegistrationID',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='StudentManagement.student'),
        ),
    ]
